name: Deploy .NET Core app to Web App PromptQuestDev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  AZURE_WEBAPP_NAME: PromptQuestDev
  AZURE_WEBAPP_PACKAGE_PATH: PromptQuest\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: PromptQuest

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Build & Publish
        run: |
          dotnet restore "${{ env.WORKING_DIRECTORY }}"
          dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
          dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.PromptQuestDev_SPN }}
          auth-type: SERVICE_PRINCIPAL

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}